import {
  Box,
  Flex,
  Button,
  Container,
  Heading,
  Center,
  Badge,
  Divider,
  Text,
  Checkbox,
  RadioGroup,
  Stack,
  Radio,
  useColorModeValue,
  Tooltip,
  useToast,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  useDisclosure,
} from '@chakra-ui/react';

import React, { useRef, useState } from 'react'
import Head from 'next/head'; ''
import FadeIn from 'react-fade-in';
import { useEffect } from 'react';
import RadioBox from '../../components/question/RadioBox';
import { QUESTION_ITEMS1 } from '../../src/data/QUESTION_ITEMS';
import SelectBox from '../../components/question/SelectBox';
import Link from 'next/link';
import Router from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
// import { addAnswer1 } from '../../features/answer/answerSlice1';
import { addAnswer1 } from '../../features/answer/answerSlice';
import { RootState } from '../../app/store';
// import { Router } from 'next/router';

type Props = {}

const Assessment1 = (props: Props) => {
  const textColor = useColorModeValue('gray.600', 'gray.300')

  const answer1 = useSelector((state: RootState) => state.answer.value1)

  const disPatch = useDispatch()

  const [value1001, setValue1001] = useState<string>(answer1[0] && answer1[0])
  const [value1002, setValue1002] = useState<string>(answer1[1] && answer1[1])
  const [value1003, setValue1003] = useState<string>(answer1[2] != undefined ? answer1[2] : '-')
  const [value1004, setValue1004] = useState<string>(answer1[3] && answer1[3])

  const toast = useToast()
  const [validate, setValidate] = useState(false)
  function validateAns() {
      if (value1001 === undefined || value1002 === undefined || value1004 === undefined) {
          toast({
              title: "รบกวนตอบคำถามให้ครบทุกข้อด้วยนะงับ 🫶",
              // description: `กรุณาตอบค`,
              status: "warning",
              variant: 'left-accent',
              duration: 3000,
              isClosable: true,
          })
      } else {
          setValidate(true);

          disPatch(addAnswer1([value1001, value1002, value1003, value1004]))

          setTimeout(() => {
              Router.push('/stresssurvey/survey2')
              toast({
                  title: "บันทึกข้อมูลสำเร็จ",
                  description: `เพศ : ${value1001}, สถานภาพ : ${value1002}, ระดับชั้นปีที่กำลังศึกษา : ${value1003}, คณะที่กำลังศึกษา : ${value1004}`,
                  status: "success",
                  duration: 7000,
                  isClosable: true,
              })
          }, 2000)
      }
  }

  return (
      <>
          <Head>
              <title>แบบสำรวจข้อมูลทั่วไป</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/keu.jpeg" />
          </Head>
          <Box pt={'60px'}>
              <Container maxW='container.sm' pt={4}>
                  <Box
                      px={[1, 1, 8, 8]}
                      pt={[1, 1, 4, 4]}
                      pb={[4, 4, 10, 10]}
                      borderRadius='lg'
                      // boxShadow={{ base: 'none', md: 'lg' }}
                  >
                      <FadeIn>
                          <Flex w='full' h='full' justify={'center'} align='center' my={4}>

                              <Heading p={3}>
                                  ข้อมูลทั่วไป
                              </Heading>

                          </Flex>
                          {/* <Text color={textColor} mx={8} fontWeight='400'>
                              <i>แบบสำรวจข้อมูลทั่วไปของผู้ทำแบบประเมิน เพื่อใช้ในการสำรวจความเครียดของนักศึกษา และบุคคลากรของมหาวิทยาลัยขอนแก่น</i>
                          </Text> */}

                          <RadioBox label={QUESTION_ITEMS1[0].label} choices={QUESTION_ITEMS1[0].choices} value={value1001} setValue={setValue1001} />
                          <RadioBox label={QUESTION_ITEMS1[1].label} choices={QUESTION_ITEMS1[1].choices} value={value1002} setValue={setValue1002} />
                          <SelectBox label={QUESTION_ITEMS1[2].label} placeholder={QUESTION_ITEMS1[2].placeholder} choices={QUESTION_ITEMS1[2].choices} value={value1003} setValue={setValue1003} boxWidth={'100px'} />
                          <SelectBox label={QUESTION_ITEMS1[3].label} placeholder={QUESTION_ITEMS1[3].placeholder} choices={QUESTION_ITEMS1[3].choices} value={value1004} setValue={setValue1004} boxWidth={'full'} />

                          <>
                              <Box
                                  mt={'24px'}
                              >
                                  <Center>
                                      <Button
                                          size='md'
                                          type='submit'
                                          colorScheme='orange'
                                          isLoading={validate}
                                          loadingText='กำลังบันทึกข้อมูล'
                                          onClick={() => { validateAns() }}
                                      >
                                          เริ่มทำแบบประเมิน
                                      </Button>
                                  </Center>
                              </Box>
                          </>
                      </FadeIn>
                  </Box>
              </Container>
          </Box>
      </>
  )
}

export default Assessment1