import type { NextPage } from 'next'
import Head from 'next/head'
import Content1 from '../components/content/content1'
import Content2 from '../components/content/content2'
import React, { useEffect, useState } from 'react'
import AboutUsComponent from '../components/aboutus'

const Home: NextPage = () => {

    const [identify, setIdentify] = useState<String>(() => {
        const ISSERVER = typeof window === "undefined";
        if (!ISSERVER) {
            const ans = localStorage.getItem("identify");
            if (ans) {
                return ans;
            } else {
                return '';
            }
        } else {
            return '';
        }
    })

    useEffect(() => {
        setIdentify(() => {
            const ISSERVER = typeof window === "undefined";
            if (!ISSERVER) {
                const ans = localStorage.getItem("identify");
                if (ans) {
                    return ans;
                } else {
                    return '';
                }
            } else {
                return '';
            }
        })
    }, [])

    useEffect(() => {
        if (identify == '') {
            localStorage.setItem("identify", `${(Math.round(Math.random() * 1000000000)).toString()}`)
        }
    }, [identify])


    return (
        <>
            <Head>
                <title>ความเขียด</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/faviconWhite.png" />
            </Head>

            <Content1 />
            <Content2 />
            <AboutUsComponent />

        </>
    )
}

export default Home
