import { Badge, Box, Button, Center, Container, Flex, Heading, List, ListIcon, ListItem, SimpleGrid, Text, useColorMode, useColorModeValue } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'

import { MdPushPin, MdSettings } from 'react-icons/md'

type Props = {}

const Stress = (props: Props) => {

    const contentCoverBGColor = useColorModeValue('#f7f5fa', 'none');
    const contentSubHeadingColor = useColorModeValue('blackAlpha.400', 'whiteAlpha.700');
    const contentTextColor = useColorModeValue('blackAlpha.900', 'whiteAlpha.900');

    return (
        <>
            <Head>
                <title>ความเครียด</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/faviconWhite.png" />
            </Head>
            <>
                <Box
                    w='full'
                    pt='70px'
                    bg={'#e9faf9'}
                >
                    <Container
                        maxW='container.lg'
                        py={4}
                    >
                        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={{ base: 0, md: 10 }}>
                            <Box
                                py={{ base: '20px', md: '80px' }}
                            >
                                <Heading
                                    size={'xl'}
                                    color={contentSubHeadingColor}
                                    my={2}
                                >
                                    # อะไรคือ ?
                                </Heading>
                                <Heading
                                    size={'4xl'}
                                    color={'#1f7b8f'}
                                    my={8}
                                >
                                    ความเครียด
                                </Heading>

                                <Text
                                    my={2}
                                    color={contentTextColor}
                                >
                                    <Badge colorScheme='purple' >ความเครียด</Badge> ก็คือ <Badge colorScheme='red' >การหดตัวของกล้ามเนื้อ</Badge>ส่วนใดส่วนหนึ่งหรือหลายส่วนของร่างกาย
                                    นั่นเอง ซึ่งทุกคนจำเป็นต้องมีอยู่เสมอในการดำรงชีวิต เช่น การทรงตัว เคลื่อนไหวทั่วๆไป
                                    มีการศึกษาพบว่าทุกครั้งที่เราคิดหรือมีอารมณ์บางอย่างเกิดขึ้นจะต้องมีการหดตัว
                                    เคลื่อนไหวของกล้ามเนื้อแห่งใดแห่งหนึ่ง ในร่างกายเกิดขึ้นควบคู่เสมอ
                                </Text>

                            </Box>
                            <Box
                                w='full'
                                h='full'
                                position='relative'

                            >
                                <Box w='full' h='full' position='absolute'></Box>
                                <Flex w='full' h='full' justify={'center'} align={'center'}>
                                    <iframe src="https://giphy.com/embed/Z3FNzSXZwOCVa" width="360" height="480" frameBorder="0" className="giphy-embed" allowFullScreen style={{ borderRadius: '8px', pointerEvents: 'none' }}></iframe>
                                </Flex>
                            </Box>

                        </SimpleGrid>
                        {/* <Center>ขอขอบคุณข้อมูลจาก : <a style={{ color: 'blue' }} href="https://www.rama.mahidol.ac.th/ramamental/generalknowledge/general/05142014-1901" target={"_blank"}>rama.mahidol.ac.th 🙏</a></Center> */}
                    </Container>

                </Box>
            </>

            <>
                <Box
                    w='full'
                    py={10}
                    bg={'white'}
                >
                    <Container
                        maxW='container.lg'
                        py={4}
                    >
                        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={{ base: 0, md: 10 }}>
                            <Box
                                w='full'
                                h='full'
                                position='relative'
                            >
                                <Box w='full' h='full' position='absolute'></Box>
                                <Flex w='full' h='full' justify={'center'} align={'center'}>
                                    <iframe src="https://giphy.com/embed/3ov9jJeFBWVWV3iwco" width="480" height="255" frameBorder="0" className="giphy-embed" allowFullScreen style={{ borderRadius: '8px', pointerEvents: 'none' }}></iframe>
                                </Flex>
                            </Box>
                            <Box
                                py={{ base: '20px', md: '10px' }}
                            >
                                <Heading
                                    size={'xl'}
                                    color={contentSubHeadingColor}
                                    my={4}
                                >
                                    # โทษของความเครียด
                                </Heading>

                                <Text
                                    my={2}
                                    color={contentTextColor}
                                >
                                    <Badge colorScheme='red'>ความเครียด</Badge> ที่เป็นโทษนั้น เป็นความเครียดชนิดที่เกินความจำเป็น แทนที่จะเป็นประโยชน์กลับกลายเป็นอุปสรรคและอันตรายต่อชีวิต
                                    เมื่อคนเราอยู่ในภาวะตึงเครียด ร่างกายก็จะเกิดความเตียมพร้อมที่จะ “สู้” หรือ “หนี” โดยที่ร่างกายมีการเปลี่ยนแปลงต่างๆ เช่น
                                </Text>
                                <List spacing={3} py={4} pl={8}>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='yellow.500' />
                                        หัวใจเต้นแรงและเร็วขึ้น เพื่อฉีดเลือดซึ่งจะนำอ๊อกซิเจนและสารอาหารต่างๆไปเลี้ยงเซลล์ทั่วร่างกาย พร้อมกับขจัดของเสียออกจากกระแสเลือดอย่างเร็ว
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='red.500' />
                                        การหายใจดีเร็วขึ้น แต่เป็นการหายใจตื้นๆ
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='blue.500' />
                                        มีการขับครีนาลีนและฮอร์โมนอื่นๆเข้าสู่กระแสเลือด
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='purple.500' />
                                        ม่านตาขยายเพื่อให้ได้รับแสงมากขึ้น
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='pink.500' />
                                        กล้ามเนื้อหดเกร็งเพื่อเตรียมการเคลื่อนไหว เตรียมสู้หรือหนี
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='orange.500' />
                                        เส้นเลือดบริเวณอวัยวะย่อยอาหารหดตัว
                                    </ListItem>
                                    <ListItem>
                                        <ListIcon as={MdPushPin} color='green.500' />
                                        เหงื่อออก เพราะมีการเผาผลาญอาหารมากขึ้น ทำให้อุณหภูมิของร่างกายเพิ่มขึ้น
                                    </ListItem>
                                </List>
                                <Text
                                    my={2}
                                    color={contentTextColor}
                                >
                                    เมื่อวิกฤตการณ์ผ่านพ้นไปร่างกายจะกลับสู่<Badge colorScheme='green'>สภาวะปกติ</Badge> แต่ความเครียดที่เป็นอันตราย ก็คือความเครียดที่เกิดขึ้น<Badge colorScheme='red'>มากเกินความจำเป็น</Badge>
                                    เมื่อเกิดแล้ว<Badge colorScheme='red'>คงอยู่เป็นประจำ</Badge> ไม่ลดหรือหายไปตามปกติ หรือเกิดขึ้นโดยไม่มีเหตุการณ์ที่เป็นการคุกคามจริงๆ

                                </Text>
                            </Box>

                        </SimpleGrid>
                        {/* <Center>ขอขอบคุณข้อมูลจาก : <a style={{ color: 'blue' }} href="https://www.rama.mahidol.ac.th/ramamental/generalknowledge/general/05142014-1901" target={"_blank"}>rama.mahidol.ac.th 🙏</a></Center> */}
                    </Container>

                </Box>
            </>
            <>
                <Box
                    w='full'
                    py={{ base: 0, md: 6 }}
                    bg={'#f0eefd'}
                >
                    <Container
                        maxW='container.lg'
                        py={4}
                    >
                        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={{ base: 0, md: 10 }}>
                            <Box
                                mt={{ base: 0, md: 10 }}
                                py={{ base: '20px', md: '10px' }}
                            >
                                <Heading
                                    size={'xl'}
                                    color={'#3c509c'}
                                    my={4}
                                >
                                    # ผลของความเครียดต่อชีวิต
                                </Heading>

                                <Text
                                    my={4}
                                    color={contentTextColor}
                                >
                                    <Badge colorScheme='purple'>ผลต่อสุขภาพทางกาย</Badge> ได้แก่ อาการไม่สบายทางกายต่างๆเช่น ปวดหัว ปวดเมื่อยตามส่วนต่างๆของร่างกาย
                                    ความผิดปกติของหัวใจ ความดันโลหิตสูง โรคกระเพาะ อาการท้องผูกท้องเสียบ่อยๆ นอนไม่หลับ หอบหืด เสื่อมสมรรถภาพทางเพศ ฯลฯ
                                </Text>
                                <Text
                                    my={6}
                                    color={contentTextColor}
                                >
                                    <Badge colorScheme='red'>ผลต่อสุขภาพจิตใจ</Badge> นำไปสู่ ความวิตกกังวล ซึมเศร้า กลัวอย่างไรเหตุผล อารมณ์ไม่มั่นคง เปลี่ยนแปลงง่าย หรือโรคประสาทบางอย่าง
                                </Text>

                            </Box>
                            <Box
                                w='full'
                                h='full'
                                position='relative'
                            >
                                <Box w='full' h='full' position='absolute'></Box>
                                <Flex w='full' h='full' justify={'center'} align={'center'}>
                                    <iframe src="https://giphy.com/embed/13PVtc14fuW3y8" width="480" height="455" frameBorder="0" className="giphy-embed" allowFullScreen style={{ borderRadius: '8px', pointerEvents: 'none' }}></iframe>
                                </Flex>
                            </Box>
                        </SimpleGrid>

                    </Container>

                </Box>
            </>
            <>
                <Box h={'70px'}>
                    <Flex align={'center'} justify={'center'} h='full'>
                        <Text
                            fontSize={'2xl'}
                        >
                            ขอขอบคุณ ข้อมูลจาก : <b><a style={{ color: 'blue' }} href="https://www.rama.mahidol.ac.th/ramamental/generalknowledge/general/05142014-1901" target={"_blank"}>rama.mahidol.ac.th 🙏</a></b>
                        </Text>
                    </Flex>
                </Box>
            </>
        </>
    )
}

export default Stress